[package]
name = "algo_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
algo_fetch = {path = "../algo_fetch"}
algo_models = {path = "../algo_models"}
futures = "0.3.31"
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"